import type { Benefit } from '@/types';

// Comprehensive caregiver benefits database
// Federal programs apply to all states, state programs filtered by user's state

export const FEDERAL_BENEFITS: Benefit[] = [
  // --- FEDERAL PROGRAMS (all states) ---
  { id: 'fed-1', benefit_name: 'Family and Medical Leave Act (FMLA)', provider: 'U.S. Department of Labor', type: 'fmla', description: 'Up to 12 weeks of unpaid, job-protected leave per year to care for a spouse, child, or parent with a serious health condition. Applies to employers with 50+ employees.', eligibility_criteria: ['Employer has 50+ employees within 75 miles', 'Worked 1,250+ hours in past 12 months', 'Employed for at least 12 months'], status: 'available' },
  { id: 'fed-2', benefit_name: 'National Family Caregiver Support Program (NFCSP)', provider: 'Administration for Community Living', type: 'federal_program', description: 'Provides respite care, counseling, training, supplemental services, and help accessing other programs for family caregivers of older adults (60+).', eligibility_criteria: ['Care recipient is 60+ years old', 'Caregiver provides informal (unpaid) care', 'Priority given to caregivers with greatest social/economic need'], application_url: 'https://eldercare.acl.gov/', status: 'available' },
  { id: 'fed-3', benefit_name: 'Medicaid Home & Community-Based Services (HCBS)', provider: 'Centers for Medicare & Medicaid Services', type: 'federal_program', description: 'Waiver programs in every state that cover home care, personal care, respite, and other services to help people stay in their homes instead of nursing facilities.', eligibility_criteria: ['Care recipient meets state Medicaid income/asset limits', 'Care recipient needs institutional-level care', 'State offers HCBS waiver slots'], application_url: 'https://www.medicaid.gov/medicaid/home-community-based-services/index.html', status: 'available' },
  { id: 'fed-4', benefit_name: 'VA Caregiver Support Program', provider: 'U.S. Department of Veterans Affairs', type: 'federal_program', description: 'Comprehensive support for caregivers of veterans including a monthly stipend, health insurance, respite care (30 days/year), mental health counseling, and training.', eligibility_criteria: ['Care recipient is a veteran', 'Veteran has serious injury/illness from military service', 'Caregiver provides personal care services'], application_url: 'https://www.caregiver.va.gov/', status: 'available' },
  { id: 'fed-5', benefit_name: 'PACE (Program of All-Inclusive Care for the Elderly)', provider: 'CMS / State Medicaid', type: 'federal_program', description: 'Comprehensive medical and social services for people 55+ who need nursing home-level care but want to stay in the community. Covers doctor visits, prescriptions, therapies, transportation, home care, and more.', eligibility_criteria: ['Care recipient is 55+ years old', 'Lives in a PACE service area', 'Needs nursing home-level care', 'Able to live safely in the community with PACE support'], application_url: 'https://www.medicare.gov/health-drug-plans/health-plans/your-coverage-options/pace', status: 'available' },
  { id: 'fed-6', benefit_name: 'Medicare Home Health Services', provider: 'Centers for Medicare & Medicaid Services', type: 'federal_program', description: 'Medicare covers part-time skilled nursing care, physical/occupational/speech therapy, medical social services, and home health aide services when ordered by a doctor.', eligibility_criteria: ['Care recipient has Medicare', 'Doctor certifies homebound status', 'Needs skilled nursing or therapy services', 'Services from a Medicare-certified agency'], application_url: 'https://www.medicare.gov/coverage/home-health-services', status: 'available' },
  { id: 'fed-7', benefit_name: 'Social Security Caregiver Credits', provider: 'Social Security Administration', type: 'federal_program', description: 'If you reduce work hours to provide care, you may be eligible for deemed wage credits that count toward your Social Security retirement benefits. Also covers divorced spouse benefits after 10+ years of marriage.', eligibility_criteria: ['Providing unpaid care that reduces your work hours', 'Had prior work history with Social Security contributions'], application_url: 'https://www.ssa.gov/caregivers/', status: 'available' },
  { id: 'fed-8', benefit_name: 'Eldercare Locator', provider: 'Administration for Community Living', type: 'nonprofit', description: 'Free national service connecting caregivers to local Area Agencies on Aging, transportation, meals, home modifications, legal assistance, and other community resources.', eligibility_criteria: ['No specific requirements — available to all caregivers'], application_url: 'https://eldercare.acl.gov/', status: 'available' },
  { id: 'fed-9', benefit_name: 'AARP Caregiving Resources', provider: 'AARP', type: 'nonprofit', description: 'Free caregiving guides, legal resources, financial planning tools, care provider directories, and community support forums for family caregivers.', eligibility_criteria: ['No specific requirements'], application_url: 'https://www.aarp.org/caregiving/', status: 'available' },
  { id: 'fed-10', benefit_name: 'Lifespan Respite Care Program', provider: 'Administration for Community Living', type: 'federal_program', description: 'Grants to states to improve respite care access for family caregivers of all ages. Helps find and fund temporary relief from caregiving duties.', eligibility_criteria: ['Live in a state with a Lifespan Respite grant', 'Provide unpaid care to a family member'], application_url: 'https://archrespite.org/lifespan-programs', status: 'available' },
];

// State-specific programs — each state's paid leave, caregiver support, respite, Medicaid waivers
export const STATE_BENEFITS: Benefit[] = [
  // --- ALABAMA ---
  { id: 'al-1', benefit_name: 'Alabama Medicaid Elderly & Disabled Waiver', provider: 'Alabama Medicaid Agency', type: 'state_program', description: 'Home and community-based services including personal care, respite, homemaker services, and adult day health for Medicaid-eligible seniors and disabled adults.', eligibility_criteria: ['Alabama resident', 'Medicaid eligible', 'Requires nursing facility level of care'], application_url: 'https://medicaid.alabama.gov/', status: 'available', state: 'AL' },
  { id: 'al-2', benefit_name: 'Alabama Respite Program', provider: 'Alabama Department of Senior Services', type: 'state_program', description: 'Provides temporary relief for primary caregivers of older adults through in-home respite, adult day care, and institutional respite services.', eligibility_criteria: ['Alabama resident', 'Primary caregiver of someone 60+'], application_url: 'https://alabamaageline.gov/', status: 'available', state: 'AL' },

  // --- ALASKA ---
  { id: 'ak-1', benefit_name: 'Alaska Personal Care Assistance Program', provider: 'Alaska DHSS', type: 'state_program', description: 'Pays family members (including spouses) to provide personal care services. One of few states that compensates family caregivers directly through Medicaid.', eligibility_criteria: ['Alaska resident', 'Medicaid eligible', 'Need assistance with daily activities'], application_url: 'https://health.alaska.gov/', status: 'available', state: 'AK' },

  // --- ARIZONA ---
  { id: 'az-1', benefit_name: 'Arizona Long Term Care System (ALTCS)', provider: 'AHCCCS', type: 'state_program', description: 'Comprehensive home and community-based services including attendant care, respite, home modifications, and personal care for Medicaid-eligible individuals.', eligibility_criteria: ['Arizona resident', 'Medicaid eligible', 'Requires institutional level of care'], application_url: 'https://www.azahcccs.gov/Members/ProgramsAndCoveredServices/ALTCS/', status: 'available', state: 'AZ' },

  // --- ARKANSAS ---
  { id: 'ar-1', benefit_name: 'Arkansas IndependentChoices', provider: 'Arkansas DHS', type: 'state_program', description: 'Consumer-directed personal care program that allows Medicaid recipients to hire their own caregivers, including family members, and direct their own care.', eligibility_criteria: ['Arkansas resident', 'Medicaid eligible', 'Need personal care assistance'], application_url: 'https://humanservices.arkansas.gov/', status: 'available', state: 'AR' },

  // --- CALIFORNIA ---
  { id: 'ca-1', benefit_name: 'California Paid Family Leave (PFL)', provider: 'CA Employment Development Department', type: 'state_program', description: 'Up to 8 weeks of partial pay (60-70% of wages, up to ~$1,620/week) to care for a seriously ill family member. Funded through employee payroll deductions.', eligibility_criteria: ['Work in California', 'Pay into State Disability Insurance (SDI)', 'Care recipient has serious health condition'], application_url: 'https://edd.ca.gov/en/disability/paid-family-leave/', status: 'available', state: 'CA' },
  { id: 'ca-2', benefit_name: 'In-Home Supportive Services (IHSS)', provider: 'CA Department of Social Services', type: 'state_program', description: 'Pays family members or other providers to deliver personal care, housekeeping, meal preparation, and other services so elderly/disabled individuals can remain at home.', eligibility_criteria: ['California resident', 'Medi-Cal eligible', 'Aged, blind, or disabled'], application_url: 'https://www.cdss.ca.gov/in-home-supportive-services', status: 'available', state: 'CA' },
  { id: 'ca-3', benefit_name: 'California Caregiver Resource Centers', provider: 'CA Department of Health Care Services', type: 'state_program', description: '11 regional centers providing free services to family caregivers including needs assessments, care planning, respite care, legal/financial consultations, and support groups.', eligibility_criteria: ['California resident', 'Family caregiver of a brain-impaired adult'], application_url: 'https://www.caregiver.org/caregiver-resource-centers-california', status: 'available', state: 'CA' },

  // --- COLORADO ---
  { id: 'co-1', benefit_name: 'Colorado FAMLI (Paid Family & Medical Leave)', provider: 'CO Department of Labor', type: 'state_program', description: 'Up to 12 weeks of paid leave (up to 90% of wages) for family caregiving. Covers care for a family member with a serious health condition.', eligibility_criteria: ['Work in Colorado', 'Earned $2,500+ in wages in the base period'], application_url: 'https://famli.colorado.gov/', status: 'available', state: 'CO' },
  { id: 'co-2', benefit_name: 'Colorado Consumer Directed Attendant Support (CDAS)', provider: 'CO HCPF', type: 'state_program', description: 'Allows Medicaid members to hire, train, and manage their own attendants including family members for personal care, homemaker, and health maintenance services.', eligibility_criteria: ['Colorado resident', 'Medicaid eligible', 'Assessed need for attendant care'], application_url: 'https://hcpf.colorado.gov/', status: 'available', state: 'CO' },

  // --- CONNECTICUT ---
  { id: 'ct-1', benefit_name: 'Connecticut Paid Family & Medical Leave', provider: 'CT Paid Leave Authority', type: 'state_program', description: 'Up to 12 weeks of paid leave at up to 95% of minimum wage for family caregiving, with additional 2 weeks for pregnancy complications.', eligibility_criteria: ['Work in Connecticut', 'Earned $100+ in the highest quarter of base period'], application_url: 'https://ctpaidleave.org/', status: 'available', state: 'CT' },
  { id: 'ct-2', benefit_name: 'Connecticut Home Care Program for Elders', provider: 'CT DSS', type: 'state_program', description: 'Home-based care services including personal care, homemaker services, adult day care, and respite for Connecticut seniors to avoid nursing home placement.', eligibility_criteria: ['Connecticut resident', '65+ years old', 'Meet income guidelines', 'Need nursing facility level of care'], application_url: 'https://portal.ct.gov/DSS', status: 'available', state: 'CT' },

  // --- DELAWARE ---
  { id: 'de-1', benefit_name: 'Delaware Paid Family & Medical Leave', provider: 'State of Delaware', type: 'state_program', description: 'Up to 12 weeks of paid leave for caregiving starting in 2026. Covers care for family members with serious health conditions.', eligibility_criteria: ['Work in Delaware', 'Employed for 12+ months', 'Employer has 25+ employees (initially)'], status: 'available', state: 'DE' },

  // --- FLORIDA ---
  { id: 'fl-1', benefit_name: 'Florida Statewide Medicaid Managed Care (Long-Term Care)', provider: 'FL Agency for Health Care Admin', type: 'state_program', description: 'Managed long-term care program covering personal care, adult day health, respite, home modifications, and caregiver training for Medicaid-eligible individuals.', eligibility_criteria: ['Florida resident', 'Medicaid eligible', '18+ years old', 'Need nursing facility level of care'], application_url: 'https://ahca.myflorida.com/', status: 'available', state: 'FL' },
  { id: 'fl-2', benefit_name: 'Florida Alzheimer\'s Disease Initiative (ADI)', provider: 'FL DOEA', type: 'state_program', description: 'Respite care services specifically for caregivers of people with Alzheimer\'s or related dementias, including in-home respite, adult day care, and facility-based respite.', eligibility_criteria: ['Florida resident', 'Caregiving for someone with dementia diagnosis', 'Income below 150% of federal poverty level'], application_url: 'https://elderaffairs.org/', status: 'available', state: 'FL' },

  // --- GEORGIA ---
  { id: 'ga-1', benefit_name: 'Georgia SOURCE (Service Options Using Resources in a Community Environment)', provider: 'GA Department of Community Health', type: 'state_program', description: 'Medicaid waiver providing home and community services including personal support, respite care, home-delivered meals, adult day health, and emergency response systems.', eligibility_criteria: ['Georgia resident', 'Medicaid eligible', '65+ or disabled', 'Need nursing facility level of care'], application_url: 'https://dch.georgia.gov/', status: 'available', state: 'GA' },
  { id: 'ga-2', benefit_name: 'Georgia Aging & Disability Resource Connection', provider: 'GA Division of Aging Services', type: 'state_program', description: 'Free one-stop resource connecting caregivers to local services including respite, meals, transportation, home modifications, legal help, and caregiver support groups.', eligibility_criteria: ['Georgia resident', 'Caregiver or older adult needing services'], application_url: 'https://aging.georgia.gov/', status: 'available', state: 'GA' },
  { id: 'ga-3', benefit_name: 'Georgia Respite Coalition', provider: 'Georgia Respite Coalition', type: 'nonprofit', description: 'Coordinates respite care services across Georgia, helps caregivers find temporary relief, and provides vouchers for respite care through participating agencies.', eligibility_criteria: ['Georgia resident', 'Primary caregiver'], application_url: 'https://www.georgiarespite.org/', status: 'available', state: 'GA' },

  // --- HAWAII ---
  { id: 'hi-1', benefit_name: 'Hawaii Kupuna Caregivers Program', provider: 'HI Executive Office on Aging', type: 'state_program', description: 'Provides employed caregivers with up to $70/day for services like adult day care, home-delivered meals, personal care, transportation, and chore services.', eligibility_criteria: ['Hawaii resident', 'Employed caregiver', 'Care recipient is 60+'], application_url: 'https://health.hawaii.gov/eoa/', status: 'available', state: 'HI' },

  // --- IDAHO ---
  { id: 'id-1', benefit_name: 'Idaho Aged & Disabled Waiver', provider: 'Idaho Medicaid', type: 'state_program', description: 'Home and community services including personal care, respite, homemaker services, adult day health, and residential habilitation for Medicaid-eligible adults.', eligibility_criteria: ['Idaho resident', 'Medicaid eligible', 'Aged or disabled'], application_url: 'https://healthandwelfare.idaho.gov/', status: 'available', state: 'ID' },

  // --- ILLINOIS ---
  { id: 'il-1', benefit_name: 'Illinois Community Care Program', provider: 'IL Department on Aging', type: 'state_program', description: 'In-home and community services to prevent nursing home placement, including homemaker, adult day service, emergency home response, and care coordination.', eligibility_criteria: ['Illinois resident', '60+ years old', 'Meet income/asset guidelines', 'Determined to be at risk of institutionalization'], application_url: 'https://ilaging.illinois.gov/', status: 'available', state: 'IL' },
  { id: 'il-2', benefit_name: 'Illinois Caregiver Support Program', provider: 'IL Department on Aging', type: 'state_program', description: 'Provides respite care, caregiver training, support groups, individual counseling, and supplemental services to family caregivers of older adults.', eligibility_criteria: ['Illinois resident', 'Caring for someone 60+', 'Or grandparent 55+ raising grandchildren'], application_url: 'https://ilaging.illinois.gov/', status: 'available', state: 'IL' },

  // --- INDIANA ---
  { id: 'in-1', benefit_name: 'Indiana Aged & Disabled Waiver', provider: 'IN FSSA', type: 'state_program', description: 'Home and community services including attendant care, respite, structured day programs, home modifications, and personal emergency response for Medicaid-eligible adults.', eligibility_criteria: ['Indiana resident', 'Medicaid eligible', 'Aged or disabled', 'Need nursing facility level of care'], application_url: 'https://www.in.gov/fssa/', status: 'available', state: 'IN' },

  // --- IOWA ---
  { id: 'ia-1', benefit_name: 'Iowa Consumer Directed Attendant Care (CDAC)', provider: 'Iowa Medicaid', type: 'state_program', description: 'Allows Medicaid members to hire and direct their own caregivers, including family members, for personal care and health-related tasks.', eligibility_criteria: ['Iowa resident', 'Medicaid eligible', 'Need assistance with daily activities'], application_url: 'https://hhs.iowa.gov/', status: 'available', state: 'IA' },

  // --- KANSAS ---
  { id: 'ks-1', benefit_name: 'Kansas HCBS Frail Elderly Waiver', provider: 'Kansas KDADS', type: 'state_program', description: 'Provides home and community services to frail elderly Kansans as an alternative to nursing home care, including personal care, respite, and adult day care.', eligibility_criteria: ['Kansas resident', 'Medicaid eligible', '65+ years old', 'Need nursing facility level of care'], application_url: 'https://kdads.ks.gov/', status: 'available', state: 'KS' },

  // --- KENTUCKY ---
  { id: 'ky-1', benefit_name: 'Kentucky Home & Community Based Waiver', provider: 'KY Cabinet for Health & Family Services', type: 'state_program', description: 'Comprehensive HCBS services including personal care, respite, adult day health, home modifications, and attendant care for Medicaid-eligible individuals.', eligibility_criteria: ['Kentucky resident', 'Medicaid eligible', 'Need institutional level of care'], application_url: 'https://chfs.ky.gov/', status: 'available', state: 'KY' },

  // --- LOUISIANA ---
  { id: 'la-1', benefit_name: 'Louisiana Community Choices Waiver', provider: 'LA Dept of Health', type: 'state_program', description: 'Self-directed personal care, respite, skilled nursing, and other services to help elderly and disabled adults live in their homes and communities.', eligibility_criteria: ['Louisiana resident', 'Medicaid eligible', 'Aged or disabled', 'Need nursing facility level of care'], application_url: 'https://ldh.la.gov/', status: 'available', state: 'LA' },

  // --- MAINE ---
  { id: 'me-1', benefit_name: 'Maine Paid Family & Medical Leave', provider: 'State of Maine', type: 'state_program', description: 'Up to 12 weeks of paid family leave for caregiving starting in 2026. Covers care for family members with serious health conditions.', eligibility_criteria: ['Work in Maine', 'Earned $6,516+ in base period'], application_url: 'https://www.maine.gov/pfml/', status: 'available', state: 'ME' },

  // --- MARYLAND ---
  { id: 'md-1', benefit_name: 'Maryland Time to Care Act (Paid Family Leave)', provider: 'State of Maryland', type: 'state_program', description: 'Up to 12 weeks of paid family leave for caregiving starting July 2026. Covers care for family members with serious health conditions.', eligibility_criteria: ['Work in Maryland', 'Worked 680+ hours in 12 months before leave'], application_url: 'https://www.maryland.gov/pages/default.aspx', status: 'available', state: 'MD' },
  { id: 'md-2', benefit_name: 'Maryland Community First Choice', provider: 'MD Dept of Health', type: 'state_program', description: 'Personal assistance services for Medicaid members, including the ability to hire and manage your own attendants for personal care and daily living activities.', eligibility_criteria: ['Maryland resident', 'Medicaid eligible', 'Need institutional level of care'], application_url: 'https://health.maryland.gov/', status: 'available', state: 'MD' },

  // --- MASSACHUSETTS ---
  { id: 'ma-1', benefit_name: 'Massachusetts Paid Family & Medical Leave', provider: 'MA DFML', type: 'state_program', description: 'Up to 12 weeks of paid family leave at up to 80% of wages for family caregiving. Maximum weekly benefit ~$1,100. Covers care for family members with serious health conditions.', eligibility_criteria: ['Work in Massachusetts', 'Meet earnings requirements', 'Care recipient has serious health condition'], application_url: 'https://www.mass.gov/pfml', status: 'available', state: 'MA' },
  { id: 'ma-2', benefit_name: 'Massachusetts Personal Care Attendant (PCA) Program', provider: 'MassHealth', type: 'state_program', description: 'Consumer-directed program that lets individuals hire and manage their own personal care attendants, including family members (except spouses), for daily living assistance.', eligibility_criteria: ['Massachusetts resident', 'MassHealth eligible', 'Need personal care assistance'], application_url: 'https://www.mass.gov/personal-care-attendant-pca-program', status: 'available', state: 'MA' },

  // --- MICHIGAN ---
  { id: 'mi-1', benefit_name: 'Michigan MI Choice Waiver', provider: 'MI DHHS', type: 'state_program', description: 'Home and community-based services including personal care, respite, home-delivered meals, adult day health, and community living supports as a nursing home alternative.', eligibility_criteria: ['Michigan resident', 'Medicaid eligible', 'Need nursing facility level of care'], application_url: 'https://www.michigan.gov/mdhhs', status: 'available', state: 'MI' },

  // --- MINNESOTA ---
  { id: 'mn-1', benefit_name: 'Minnesota Paid Family & Medical Leave', provider: 'State of Minnesota', type: 'state_program', description: 'Up to 12 weeks of paid leave for family caregiving starting in 2026. Covers care for family members with serious health conditions.', eligibility_criteria: ['Work in Minnesota', 'Meet earnings requirements'], application_url: 'https://mn.gov/deed/paidleave/', status: 'available', state: 'MN' },
  { id: 'mn-2', benefit_name: 'Minnesota Consumer Directed Community Supports (CDCS)', provider: 'MN DHS', type: 'state_program', description: 'Flexible budget for participants to design their own services, hire caregivers (including family), purchase goods, and direct their care at home.', eligibility_criteria: ['Minnesota resident', 'Medicaid eligible', 'Assessed need for waiver services'], application_url: 'https://mn.gov/dhs/', status: 'available', state: 'MN' },

  // --- MISSISSIPPI ---
  { id: 'ms-1', benefit_name: 'Mississippi Elderly & Disabled Waiver', provider: 'MS Division of Medicaid', type: 'state_program', description: 'Home and community services including personal care, respite, adult day care, and homemaker services for Medicaid-eligible elderly and disabled individuals.', eligibility_criteria: ['Mississippi resident', 'Medicaid eligible', 'Need nursing facility level of care'], application_url: 'https://medicaid.ms.gov/', status: 'available', state: 'MS' },

  // --- MISSOURI ---
  { id: 'mo-1', benefit_name: 'Missouri Aged & Disabled Waiver', provider: 'MO HealthNet', type: 'state_program', description: 'Home and community services including personal care, respite, adult day care, and home modifications for seniors and disabled adults on Medicaid.', eligibility_criteria: ['Missouri resident', 'Medicaid eligible', 'Aged or disabled'], application_url: 'https://mydss.mo.gov/', status: 'available', state: 'MO' },

  // --- MONTANA ---
  { id: 'mt-1', benefit_name: 'Montana Big Sky Waiver', provider: 'MT DPHHS', type: 'state_program', description: 'Personal assistance, respite, adult day services, and other home-based supports for elderly and physically disabled Medicaid members.', eligibility_criteria: ['Montana resident', 'Medicaid eligible', 'Need nursing facility level of care'], application_url: 'https://dphhs.mt.gov/', status: 'available', state: 'MT' },

  // --- NEBRASKA ---
  { id: 'ne-1', benefit_name: 'Nebraska Aged & Disabled Waiver', provider: 'NE DHHS', type: 'state_program', description: 'Home and community services including personal assistance, respite, adult day, chore services, and home modifications for Medicaid-eligible adults.', eligibility_criteria: ['Nebraska resident', 'Medicaid eligible', '65+ or disabled'], application_url: 'https://dhhs.ne.gov/', status: 'available', state: 'NE' },

  // --- NEVADA ---
  { id: 'nv-1', benefit_name: 'Nevada Home & Community Based Waiver for Frail Elderly', provider: 'NV DHCFP', type: 'state_program', description: 'Personal care, homemaker, respite, adult day care, and case management services for Medicaid-eligible frail elderly individuals.', eligibility_criteria: ['Nevada resident', 'Medicaid eligible', '65+ years old', 'Need nursing facility level of care'], application_url: 'https://dhcfp.nv.gov/', status: 'available', state: 'NV' },

  // --- NEW HAMPSHIRE ---
  { id: 'nh-1', benefit_name: 'New Hampshire Choices for Independence Waiver', provider: 'NH DHHS', type: 'state_program', description: 'Home and community services including personal care, respite, adult day, home modifications, and attendant care as alternatives to nursing facility placement.', eligibility_criteria: ['New Hampshire resident', 'Medicaid eligible', 'Need nursing facility level of care'], application_url: 'https://www.dhhs.nh.gov/', status: 'available', state: 'NH' },

  // --- NEW JERSEY ---
  { id: 'nj-1', benefit_name: 'New Jersey Family Leave Insurance', provider: 'NJ Department of Labor', type: 'state_program', description: 'Up to 12 weeks of paid leave at 85% of average weekly wage (up to ~$1,025/week) for family caregiving. One of the most generous state programs.', eligibility_criteria: ['Work in New Jersey', 'Paid into NJ FLI through payroll', 'Care recipient has serious health condition'], application_url: 'https://myleavebenefits.nj.gov/', status: 'available', state: 'NJ' },
  { id: 'nj-2', benefit_name: 'New Jersey Statewide Respite Care Program', provider: 'NJ DHSS', type: 'state_program', description: 'Provides temporary relief for caregivers through in-home respite, adult day programs, and short-term facility stays regardless of income.', eligibility_criteria: ['New Jersey resident', 'Primary caregiver of an adult 18+'], application_url: 'https://www.nj.gov/humanservices/', status: 'available', state: 'NJ' },

  // --- NEW MEXICO ---
  { id: 'nm-1', benefit_name: 'New Mexico Mi Via Self-Directed Waiver', provider: 'NM Human Services Dept', type: 'state_program', description: 'Self-directed waiver allowing participants to hire their own caregivers including family members, set wages, and control their care budget.', eligibility_criteria: ['New Mexico resident', 'Medicaid eligible', 'Need institutional level of care'], application_url: 'https://www.hsd.state.nm.us/', status: 'available', state: 'NM' },

  // --- NEW YORK ---
  { id: 'ny-1', benefit_name: 'New York Paid Family Leave', provider: 'NY Workers Compensation Board', type: 'state_program', description: 'Up to 12 weeks of paid leave at 67% of average weekly wage (up to ~$1,151/week) for family caregiving. Covers care for a family member with a serious health condition.', eligibility_criteria: ['Work in New York', 'Full-time: 26+ weeks employed', 'Part-time: 175+ days worked', 'Care recipient has serious health condition'], application_url: 'https://paidfamilyleave.ny.gov/', status: 'available', state: 'NY' },
  { id: 'ny-2', benefit_name: 'New York Consumer Directed Personal Assistance (CDPA)', provider: 'NY DOH', type: 'state_program', description: 'Allows Medicaid recipients to hire, train, and supervise their own personal assistants including family members (except spouses) for personal care services.', eligibility_criteria: ['New York resident', 'Medicaid eligible', 'Need personal care services', 'Self-directing capability'], application_url: 'https://www.health.ny.gov/', status: 'available', state: 'NY' },

  // --- NORTH CAROLINA ---
  { id: 'nc-1', benefit_name: 'NC Community Alternatives Program (CAP/DA)', provider: 'NC DHHS', type: 'state_program', description: 'In-home care services including personal care, respite, home modifications, adult day health, and training for Medicaid-eligible disabled adults as a nursing home alternative.', eligibility_criteria: ['North Carolina resident', 'Medicaid eligible', 'Disabled adult', 'Need institutional level of care'], application_url: 'https://www.ncdhhs.gov/', status: 'available', state: 'NC' },
  { id: 'nc-2', benefit_name: 'NC Project C.A.R.E.', provider: 'NC Division of Aging and Adult Services', type: 'state_program', description: 'Caregiver Alternative to Running on Empty — provides respite, supplemental services, consumable supplies, and support to family caregivers of adults with dementia.', eligibility_criteria: ['North Carolina resident', 'Caring for someone with dementia diagnosis'], application_url: 'https://www.ncdhhs.gov/divisions/aging', status: 'available', state: 'NC' },

  // --- NORTH DAKOTA ---
  { id: 'nd-1', benefit_name: 'North Dakota SPED (Service Payments for Elderly & Disabled)', provider: 'ND DHS', type: 'state_program', description: 'State-funded program providing in-home services, adult day care, and respite care for elderly and disabled individuals who don\'t qualify for Medicaid.', eligibility_criteria: ['North Dakota resident', '18+ years old', 'Need assistance with daily activities', 'Income below state guidelines'], application_url: 'https://www.nd.gov/dhs/', status: 'available', state: 'ND' },

  // --- OHIO ---
  { id: 'oh-1', benefit_name: 'Ohio PASSPORT (Pre-Admission Screening System Providing Options & Resources Today)', provider: 'OH Department of Aging', type: 'state_program', description: 'Comprehensive home care program providing personal care, homemaker services, respite, adult day care, home-delivered meals, and emergency response systems.', eligibility_criteria: ['Ohio resident', 'Medicaid eligible', '60+ years old', 'Need nursing facility level of care'], application_url: 'https://aging.ohio.gov/', status: 'available', state: 'OH' },

  // --- OKLAHOMA ---
  { id: 'ok-1', benefit_name: 'Oklahoma ADvantage Waiver', provider: 'OK Health Care Authority', type: 'state_program', description: 'Home and community services including personal care, respite, adult day health, and home modifications for Medicaid-eligible aged and disabled adults.', eligibility_criteria: ['Oklahoma resident', 'Medicaid eligible', 'Aged or disabled', 'Need nursing facility level of care'], application_url: 'https://oklahoma.gov/ohca.html', status: 'available', state: 'OK' },

  // --- OREGON ---
  { id: 'or-1', benefit_name: 'Oregon Paid Family & Medical Leave', provider: 'OR Employment Department', type: 'state_program', description: 'Up to 12 weeks of paid leave at up to 100% of average weekly wage for family caregiving. One of the most generous programs in the country.', eligibility_criteria: ['Work in Oregon', 'Earned $1,000+ in base year', 'Care recipient has serious health condition'], application_url: 'https://paidleave.oregon.gov/', status: 'available', state: 'OR' },
  { id: 'or-2', benefit_name: 'Oregon Project Independence', provider: 'OR DHS', type: 'state_program', description: 'State-funded program providing in-home services for seniors who don\'t qualify for Medicaid, including personal care, housekeeping, and respite.', eligibility_criteria: ['Oregon resident', '60+ years old', 'Need help with daily activities', 'Not Medicaid eligible'], application_url: 'https://www.oregon.gov/dhs/', status: 'available', state: 'OR' },

  // --- PENNSYLVANIA ---
  { id: 'pa-1', benefit_name: 'Pennsylvania OPTIONS Program', provider: 'PA Department of Aging', type: 'state_program', description: 'In-home services including personal care, home-delivered meals, adult day care, and respite for seniors to maintain independence and avoid nursing home placement.', eligibility_criteria: ['Pennsylvania resident', '60+ years old', 'Need long-term care services', 'Income-eligible'], application_url: 'https://www.aging.pa.gov/', status: 'available', state: 'PA' },
  { id: 'pa-2', benefit_name: 'Pennsylvania Caregiver Support Program', provider: 'PA Department of Aging', type: 'state_program', description: 'Provides reimbursement for caregiver expenses, respite care, counseling, and supplemental services to family caregivers of older adults.', eligibility_criteria: ['Pennsylvania resident', 'Primary caregiver of someone 60+', 'Caregiver income-eligible'], application_url: 'https://www.aging.pa.gov/', status: 'available', state: 'PA' },

  // --- RHODE ISLAND ---
  { id: 'ri-1', benefit_name: 'Rhode Island Temporary Caregiver Insurance (TCI)', provider: 'RI Department of Labor', type: 'state_program', description: 'Up to 6 weeks of paid leave (~60% of wages) for family caregiving. Rhode Island was the third state to offer paid family leave.', eligibility_criteria: ['Work in Rhode Island', 'Earned $15,600+ or $2,600+ in highest quarter', 'Care recipient has serious health condition'], application_url: 'https://dlt.ri.gov/tci', status: 'available', state: 'RI' },

  // --- SOUTH CAROLINA ---
  { id: 'sc-1', benefit_name: 'South Carolina Community Long Term Care', provider: 'SC DHHS', type: 'state_program', description: 'Medicaid waiver providing personal care, respite, adult day health care, and home-delivered meals for elderly and disabled adults as a nursing home alternative.', eligibility_criteria: ['South Carolina resident', 'Medicaid eligible', 'Need nursing facility level of care'], application_url: 'https://www.scdhhs.gov/', status: 'available', state: 'SC' },

  // --- SOUTH DAKOTA ---
  { id: 'sd-1', benefit_name: 'South Dakota CHOICES Waiver', provider: 'SD DSS', type: 'state_program', description: 'Home and community services including personal care, respite, adult companion, homemaker services, and assistive technology for Medicaid-eligible adults.', eligibility_criteria: ['South Dakota resident', 'Medicaid eligible', 'Aged or disabled', 'Need nursing facility level of care'], application_url: 'https://dss.sd.gov/', status: 'available', state: 'SD' },

  // --- TENNESSEE ---
  { id: 'tn-1', benefit_name: 'TennCare CHOICES Program', provider: 'TN Division of TennCare', type: 'state_program', description: 'Home and community-based services including personal care, attendant care, respite, adult day care, and home modifications for TennCare-eligible adults.', eligibility_criteria: ['Tennessee resident', 'TennCare eligible', 'Need nursing facility level of care'], application_url: 'https://www.tn.gov/tenncare.html', status: 'available', state: 'TN' },

  // --- TEXAS ---
  { id: 'tx-1', benefit_name: 'Texas STAR+PLUS HCBS', provider: 'TX Health and Human Services', type: 'state_program', description: 'Managed care program providing personal attendant services, respite, adult day care, home modifications, and adaptive aids for Medicaid-eligible adults.', eligibility_criteria: ['Texas resident', 'Medicaid eligible', '21+ years old', 'Aged, blind, or disabled'], application_url: 'https://www.hhs.texas.gov/', status: 'available', state: 'TX' },
  { id: 'tx-2', benefit_name: 'Texas Lifespan Respite Care Program', provider: 'TX Health and Human Services', type: 'state_program', description: 'Provides vouchers for temporary respite care to family caregivers, helping pay for in-home aides, adult day care, or short-term facility care.', eligibility_criteria: ['Texas resident', 'Primary family caregiver', 'Care recipient has chronic condition or disability'], application_url: 'https://www.hhs.texas.gov/', status: 'available', state: 'TX' },

  // --- UTAH ---
  { id: 'ut-1', benefit_name: 'Utah Aging Waiver', provider: 'UT Department of Health', type: 'state_program', description: 'Home and community services including personal care, respite, companion services, chore services, and home-delivered meals for Medicaid-eligible elderly.', eligibility_criteria: ['Utah resident', 'Medicaid eligible', '65+ years old', 'Need nursing facility level of care'], application_url: 'https://medicaid.utah.gov/', status: 'available', state: 'UT' },

  // --- VERMONT ---
  { id: 'vt-1', benefit_name: 'Vermont Choices for Care', provider: 'VT DAIL', type: 'state_program', description: 'Comprehensive long-term care program providing personal care, respite, adult day, companion services, and the option to hire family members as paid caregivers.', eligibility_criteria: ['Vermont resident', 'Medicaid eligible', 'Need long-term care services'], application_url: 'https://dail.vermont.gov/', status: 'available', state: 'VT' },

  // --- VIRGINIA ---
  { id: 'va-1', benefit_name: 'Virginia Consumer-Directed Services', provider: 'VA DMAS', type: 'state_program', description: 'Allows Medicaid members to hire, train, and supervise their own personal care attendants including family members for assistance with daily activities.', eligibility_criteria: ['Virginia resident', 'Medicaid eligible', 'Need personal care assistance'], application_url: 'https://www.dmas.virginia.gov/', status: 'available', state: 'VA' },

  // --- WASHINGTON ---
  { id: 'wa-1', benefit_name: 'Washington Paid Family & Medical Leave', provider: 'WA Employment Security', type: 'state_program', description: 'Up to 12 weeks of paid leave at up to 90% of wages for family caregiving. Maximum weekly benefit ~$1,456. One of the best programs nationally.', eligibility_criteria: ['Work in Washington', 'Worked 820+ hours in qualifying period', 'Care recipient has serious health condition'], application_url: 'https://paidleave.wa.gov/', status: 'available', state: 'WA' },
  { id: 'wa-2', benefit_name: 'Washington COPES Waiver', provider: 'WA DSHS', type: 'state_program', description: 'Community Options Program Entry System — home care, personal care, respite, adult day health, home modifications, and skilled nursing for Medicaid-eligible adults.', eligibility_criteria: ['Washington resident', 'Medicaid eligible', 'Need nursing facility level of care'], application_url: 'https://www.dshs.wa.gov/', status: 'available', state: 'WA' },

  // --- WEST VIRGINIA ---
  { id: 'wv-1', benefit_name: 'West Virginia Aged & Disabled Waiver', provider: 'WV Bureau for Medical Services', type: 'state_program', description: 'Personal care, respite, adult day health care, homemaker services, and case management for Medicaid-eligible aged and disabled individuals.', eligibility_criteria: ['West Virginia resident', 'Medicaid eligible', 'Need nursing facility level of care'], application_url: 'https://dhhr.wv.gov/bms/', status: 'available', state: 'WV' },

  // --- WISCONSIN ---
  { id: 'wi-1', benefit_name: 'Wisconsin Family Care', provider: 'WI DHS', type: 'state_program', description: 'Comprehensive managed care program providing personal care, respite, adult day, home modifications, supportive home care, and daily living skills training.', eligibility_criteria: ['Wisconsin resident', 'Medicaid eligible or meet functional/financial criteria', 'Elderly, physically disabled, or developmentally disabled'], application_url: 'https://www.dhs.wisconsin.gov/familycare/', status: 'available', state: 'WI' },

  // --- WYOMING ---
  { id: 'wy-1', benefit_name: 'Wyoming Community Choices Waiver', provider: 'WY Department of Health', type: 'state_program', description: 'Home and community services including personal care, respite, adult day care, and homemaker services for Medicaid-eligible aged and disabled adults.', eligibility_criteria: ['Wyoming resident', 'Medicaid eligible', 'Need nursing facility level of care'], application_url: 'https://health.wyo.gov/', status: 'available', state: 'WY' },

  // --- DISTRICT OF COLUMBIA ---
  { id: 'dc-1', benefit_name: 'DC Universal Paid Leave', provider: 'DC Department of Employment Services', type: 'state_program', description: 'Up to 12 weeks of paid family leave at 90% of wages (up to $1,118/week) for caregiving. One of the most generous programs in the nation.', eligibility_criteria: ['Work in Washington, DC', 'Care recipient has serious health condition'], application_url: 'https://does.dc.gov/page/dc-paid-family-leave', status: 'available', state: 'DC' },
  { id: 'dc-2', benefit_name: 'DC Elderly & Persons with Disabilities Waiver', provider: 'DC Department of Health Care Finance', type: 'state_program', description: 'Personal care, respite, adult day health, home-delivered meals, and environmental modifications for Medicaid-eligible elderly and disabled DC residents.', eligibility_criteria: ['DC resident', 'Medicaid eligible', '65+ or disabled', 'Need nursing facility level of care'], application_url: 'https://dhcf.dc.gov/', status: 'available', state: 'DC' },
];

// Returns all benefits relevant to a user's state
export function getBenefitsForState(state: string): Benefit[] {
  const stateBenefits = STATE_BENEFITS.filter(b => b.state === state);
  return [...FEDERAL_BENEFITS, ...stateBenefits];
}
